version: '3'

volumes:
  grafana-data:
    driver: local

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - "GF_SERVER_HTTP_PORT=3000" #Ensure to make it the same port you use above.
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
